resources:
- name: etcher-git-repository
  type: git
  source:
    uri: https://github.com/resin-io/etcher.git
    branch: concourse-test
    disable_ci_skip: true

jobs:
- name: etcher-tests

  # Make the job results accessible to
  # un-authenticated users
  public: true

  plan:
  - get: etcher-git-repository

    # Trigger this job if the resource has a new
    # version. If this is false, the job can only
    # be started from the web UI.
    trigger: true

  - task: dependencies
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: boron-wheezy
      inputs:
        - name: etcher-git-repository
      run:
        path: sh
        args:
        - -exc
        - |
          echo "deb http://http.debian.net/debian wheezy-backports main" >> /etc/apt/sources.list
          apt-get update
          apt-get install -y jq curl libudev-dev python python-dev python-setuptools
          curl "https://pypi.python.org/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz" > pip-9.0.1.tar.gz
          tar xvfz pip-9.0.1.tar.gz
          cd pip-9.0.1
          python setup.py install
          cd ..
          pip install -r etcher-git-repository/requirements.txt
          cd etcher-git-repository
          make electron-develop

  - task: lint
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: pwd
        args: []
      inputs:
        - name: etcher-git-repository
