resources:
- name: etcher
  type: git
  source:
    uri: https://github.com/resin-io/etcher.git
    branch: concourse-test
    disable_ci_skip: true

jobs:
- name: tests-darwin

  # Make the job results accessible to
  # un-authenticated users
  public: true

  plan:
  - get: etcher

    # Trigger this job if the resource has a new
    # version. If this is false, the job can only
    # be started from the web UI.
    trigger: true

  - task: dependencies
    config:
      platform: darwin
      inputs:
        - name: etcher
      outputs:
        - name: node_modules
      run:
        path: sh
        args:
          - -exc
          - |
            cd etcher
            make electron-develop
            mv node_modules ../node_modules

  # TODO: Use an aggregate to parallelize these

  - task: lint
    config:
      platform: darwin
      inputs:
        - name: etcher
        - name: node_modules
      run:
        path: sh
        args:
          - -exc
          - |
            ls
            cd etcher
            ./ci/run-make.sh ../node_modules lint

  - task: test
    config:
      platform: darwin
      inputs:
        - name: etcher
      run:
        path: make
        dir: etcher
        args: [ test ]

  - task: sanity-checks
    config:
      platform: darwin
      inputs:
        - name: etcher
      run:
        path: make
        dir: etcher
        args: [ sanity-checks ]
